"""
Django settings for skinpredictor project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import torch
import numpy as np
import random
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv


# Define the base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Explicitly load the .env file from the base directory
# env_path = BASE_DIR / '.env'
# load_dotenv(dotenv_path=env_path)
# print("API Key from .env:", os.getenv("GOOGLE_API_KEY"))

# --- START: Deterministic Setup ---
SEED = 42

def set_deterministic_environment(seed):
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
    torch.set_num_threads(1)
    torch.set_num_interop_threads(1)
    np.random.seed(seed)
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)

set_deterministic_environment(SEED)

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.environ.get('SECRET_KEY', 'your_insecure_default_key_for_dev')

DEBUG = True
# ALLOWED_HOSTS = ['glow-genie-organic-skin-care.onrender.com', 'localhost', '127.0.0.1','192.168.100.10']
ALLOWED_HOSTS = ['*','192.168.100.10:8000']
CSRF_TRUSTED_ORIGINS = ['https://glow-genie-organic-skin-care.onrender.com']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'jsoneditor',
    'predictor',
    # 'users',
    'reviews',
    'skin_identifier',
    'chatbot',
    # 'chatbot_api',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',
    'users.apps.UsersConfig', 
]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # CORS should be early (before CommonMiddleware)
    'corsheaders.middleware.CorsMiddleware',

    # Sessions + auth in this order (critical so login persists)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Allauth middleware (if used). Put after auth/messages.
    'allauth.account.middleware.AccountMiddleware',
]

LOGIN_URL = 'auth_page'
LOGIN_REDIRECT_URL = '/'
CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'skinpredictor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'predictor': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'chatbot': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

WSGI_APPLICATION = 'skinpredictor.wsgi.application'

# --- DATABASE CONFIGURATION FOR PYTHONANYWHERE POSTGRESQL ---
# This configuration is for connecting to your PostgreSQL database on PythonAnywhere.
# You will need to replace the placeholders with your actual database details.
# Get these from the "Databases" tab on your PythonAnywhere dashboard.
# You need to create a database and a user first.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'skindb',
        'USER': 'alina',
        'PASSWORD': 'MyDjangoPass!123',
        'HOST': 'localhost', # or '127.0.0.1'
        'PORT': '5432',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
CONTACT_EMAIL = 'your_recipient_email@example.com'

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'skinpredictor', 'static'),
]
# settings.py

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if not DEBUG:
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True



AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# 2. Set the redirect to your new view to handle role assignment
LOGIN_URL = 'auth_page'
LOGIN_REDIRECT_URL = 'social_auth_complete' # <-- Correct Redirection URL
ACCOUNT_LOGOUT_REDIRECT_URL = 'auth_page'
SOCIALACCOUNT_ADAPTER = 'users.adapter.CustomSocialAccountAdapter'

SECRET_KEY = 'django-insecure-f(me9chu@b@6^&_93paq+msm8=ar%chn1nia5*b=9!^2uz$cik'
# GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

# SOCIALACCOUNT_PROVIDERS = {
#     'google' : {
#         'APP':{
#             'client_id' :'508830518870-lj9j58j5ejtpt5bb2dg9i6s48nssac9v.apps.googleusercontent.com',
#             'secret' : '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',
#             'key' : '',
#         }
#     },
#     'facebook': {
#         'APP': {
#             'client_id': '672290478556066',
#             'secret': 'b1260224375be52b537fe8f1139393cb',
#             'key': ''
#         }
#     },
#     'github': {
#         'APP': {
#             'client_id': 'Ov23lix7VAUhUROdoVPt',
#             'secret': '4749e7a4e072407d8cac6338cd6854c6cfe24769',
#             'key': ''
#         }
#     }
    
    
# }


# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:8000",
#     "https://glow-genie-organic-skin-care.onrender.com",
#     "http://192.168.100.10:8000",
# ]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.CustomUser'
